export const FOODS = [
  // ── 庶民之味 ──
  // 台式經典
  { name: "滷肉飯", tier: "庶民" },
  { name: "雞腿便當", tier: "庶民" },
  { name: "排骨飯", tier: "庶民" },
  { name: "鍋燒意麵", tier: "庶民" },
  { name: "咖哩飯", tier: "庶民" },
  { name: "水餃", tier: "庶民" },
  { name: "炒飯", tier: "庶民" },
  { name: "漢堡", tier: "庶民" },
  { name: "燒臘飯", tier: "庶民" },
  { name: "涼麵", tier: "庶民" },
  { name: "肉圓", tier: "庶民" },
  { name: "自助餐", tier: "庶民" },
  { name: "乾麵", tier: "庶民" },
  { name: "肉燥飯", tier: "庶民" },
  { name: "蔥油餅加蛋", tier: "庶民" },
  { name: "鍋貼", tier: "庶民" },
  { name: "陽春麵", tier: "庶民" },
  { name: "控肉飯", tier: "庶民" },
  { name: "魯味", tier: "庶民" },
  { name: "臭豆腐", tier: "庶民" },
  { name: "蚵仔麵線", tier: "庶民" },
  { name: "大腸包小腸", tier: "庶民" },
  { name: "米粉湯", tier: "庶民" },
  { name: "筒仔米糕", tier: "庶民" },
  { name: "雞肉飯", tier: "庶民" },
  { name: "虱目魚粥", tier: "庶民" },
  { name: "刈包", tier: "庶民" },
  { name: "潤餅", tier: "庶民" },
  { name: "碗粿", tier: "庶民" },

  // 早餐店系列
  { name: "早餐店蛋餅", tier: "庶民" },
  { name: "早餐店鐵板麵", tier: "庶民" },
  { name: "總匯三明治", tier: "庶民" },
  { name: "早餐店漢堡", tier: "庶民" },
  { name: "蘿蔔糕", tier: "庶民" },
  { name: "飯糰", tier: "庶民" },
  { name: "燒餅油條", tier: "庶民" },

  // ── 小資享受 ──
  // 日韓料理
  { name: "牛肉麵", tier: "小資" },
  { name: "拉麵", tier: "小資" },
  { name: "壽司", tier: "小資" },
  { name: "蛋包飯", tier: "小資" },
  { name: "韓式拌飯", tier: "小資" },
  { name: "丼飯", tier: "小資" },
  { name: "定食", tier: "小資" },
  { name: "咖哩烏龍麵", tier: "小資" },
  { name: "豬排飯", tier: "小資" },
  { name: "味噌拉麵", tier: "小資" },
  { name: "韓式豆腐鍋", tier: "小資" },
  { name: "韓式部隊鍋", tier: "小資" },
  { name: "日式咖哩", tier: "小資" },
  { name: "手卷", tier: "小資" },
  { name: "韓式冷麵", tier: "小資" },

  // 東南亞料理
  { name: "越南河粉", tier: "小資" },
  { name: "泰式打拋豬", tier: "小資" },
  { name: "印度咖哩", tier: "小資" },
  { name: "海南雞飯", tier: "小資" },
  { name: "叻沙", tier: "小資" },
  { name: "泰式綠咖哩", tier: "小資" },
  { name: "越南春捲", tier: "小資" },
  { name: "肉骨茶", tier: "小資" },
  { name: "椒麻雞飯", tier: "小資" },

  // 西式料理
  { name: "義大利麵", tier: "小資" },
  { name: "早午餐", tier: "小資" },
  { name: "墨西哥捲餅", tier: "小資" },
  { name: "鐵板燒", tier: "小資" },
  { name: "漢堡排定食", tier: "小資" },
  { name: "燉飯", tier: "小資" },
  { name: "焗烤飯", tier: "小資" },
  { name: "班尼迪克蛋", tier: "小資" },

  // 中式菜系
  { name: "川菜", tier: "小資" },
  { name: "港式燒臘", tier: "小資" },
  { name: "上海菜", tier: "小資" },
  { name: "客家菜", tier: "小資" },
  { name: "粵菜", tier: "小資" },
  { name: "北京烤鴨捲", tier: "小資" },
  { name: "酸菜魚", tier: "小資" },
  { name: "麻婆豆腐飯", tier: "小資" },
  { name: "紅燒牛腩飯", tier: "小資" },

  // 港式
  { name: "港式點心", tier: "小資" },
  { name: "港式茶餐廳", tier: "小資" },
  { name: "叉燒飯", tier: "小資" },

  // ── 今日放縱 ──
  { name: "鹹酥雞", tier: "放縱" },
  { name: "火鍋", tier: "放縱" },
  { name: "披薩", tier: "放縱" },
  { name: "珍珠奶茶當正餐", tier: "放縱" },
  { name: "韓式炸雞", tier: "放縱" },
  { name: "燒肉丼", tier: "放縱" },
  { name: "麻辣燙", tier: "放縱" },
  { name: "炸物拼盤", tier: "放縱" },
  { name: "吃到飽", tier: "放縱" },
  { name: "壽喜燒", tier: "放縱" },
  { name: "麻辣火鍋", tier: "放縱" },
  { name: "韓式烤肉", tier: "放縱" },
  { name: "炸雞排", tier: "放縱" },
  { name: "起司瀑布漢堡", tier: "放縱" },
  { name: "拉麵加麵加蛋", tier: "放縱" },

  // ── 苦行修練 ──
  { name: "泡麵", tier: "苦行" },
  { name: "便利商店微波便當", tier: "苦行" },
  { name: "三明治", tier: "苦行" },
  { name: "沙拉", tier: "苦行" },
  { name: "御飯糰兩顆", tier: "苦行" },
  { name: "蘇打餅配黑咖啡", tier: "苦行" },
  { name: "昨天的剩菜", tier: "苦行" },
  { name: "白吐司配水", tier: "苦行" },
  { name: "能量棒", tier: "苦行" },
  { name: "茶葉蛋兩顆", tier: "苦行" },

  // ── 傳說級 ──
  { name: "高級餐廳", tier: "傳說" },
];

export const TIER_LABELS = {
  "庶民": "庶民之味",
  "小資": "小資享受",
  "放縱": "今日放縱",
  "苦行": "苦行修練",
  "傳說": "✦ 傳說級 ✦",
};
